spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/catering_identa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true